name: formularios_antropoindicadores
description: App de formulário para o PROJETO INDICADORES ANTRÓPICOS / ANTROPOINDICADORES da UFPA

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  adaptive_theme: ^3.3.0
  cupertino_icons: ^1.0.2
  csv: ^5.0.0
  file: ^6.1.4
  file_manager: ^1.0.0
  flow_builder: ^0.0.5
  flutter_colorpicker: ^1.0.3
  flutter_hooks: ^0.18.0
  flutter_riverpod: ^2.3.6
  freezed: ^2.3.5
  path_provider: ^2.0.6
  permission_handler: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/questions.json
    - assets/INDICADORES_ANTROPICOS-Manual_do_Usuário_e_Guia_de_Campo v2.pdf
